name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@main
        with:
          node-version: 16.7

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@main
        # This step should be check on alpha, beta or stable releases, publish Workflow Script dependant on the release type
        # with:
        #   # This expects you to have a script called release which does a build for your packages and calls changeset publish
        #   publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: GChat or Discord Message for Release
        if: steps.changesets.outputs.published == 'true'
        # This could be a GChat or Discord accouncement for the release
        run: echo "Release published to npm"
